export default {
  FETCH_MESSAGE_REQUEST: 'FETCH_MESSAGE_REQUEST',
  FETCH_MESSAGE_SUCCESS: 'FETCH_MESSAGE_SUCCESS',
  FETCH_MESSAGE_FAILURE: 'FETCH_MESSAGE_FAILURE',
  FETCH_WALL_MESSAGES_REQUEST: 'FETCH_WALL_MESSAGES_REQUEST',
  FETCH_WALL_MESSAGES_SUCCESS: 'FETCH_WALL_MESSAGES_SUCCESS',
  FETCH_WALL_MESSAGES_FAILURE: 'FETCH_WALL_MESSAGES_FAILURE',
  CLEAR_MESSAGE: 'CLEAR_MESSAGE',
};

